services:
  api:
    platform: linux/amd64
    build: ./server
    container_name: ap_api
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_URI=mongodb://mongodb:27017
      - DB_NAME=air-pollution
    depends_on:
      - mongodb
    links:
      - mongodb:db
    volumes:
      - ./server:/usr/src/app

  api_docs:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile-api-doc
    container_name: ap_api_docs
    ports:
      - 8081:80
    volumes:
      - ./server:/usr/src/app

  frontend:
    platform: linux/amd64
    build: ./airPollution
    container_name: ap_frontend
    ports:
      - 4200:4200
    volumes:
      - ./airPollution:/usr/src/app

  mongodb:
    platform: linux/amd64
    image: mongo:3.6-jessie
    container_name: ap_mongodb
    volumes:
      - ./docker_data/mongodb:/data/db
    ports:
      - 27017:27017
