services:
  api:
    build: ./server
    container_name: ap_api
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_URI=mongodb://mongodb:27017
      - DB_NAME=air-pollution
    depends_on:
      - mongodb
    links:
      - mongodb:db

  api_docs:
    build:
      context: ./server
      dockerfile: Dockerfile-api-doc
    container_name: ap_api_docs
    ports:
      - 8081:80

  frontend:
    build: ./airPollution
    container_name: ap_frontend
    ports:
      - 4200:4200

  mongodb:
    image: mongo:4.4
    container_name: ap_mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb_data:
