[uwsgi]
chdir=/usr/src/app
module=air_pollution.api.air_app:pandasApi
#socket = /tmp/uwsgi.sock
#chown-socket = nginx:nginx
socket = :8001
chmod-socket = 664
max-requests=5000
daemonize=/var/log/uwsgi/ap-uwsgi.log