[supervisord]
nodaemon = true
strip_ansi = true

[program:uwsgi]
command = pipenv run uwsgi --ini /usr/src/app/uwsgi.ini  --die-on-term
directory = /usr/src/app
autostart = true
autorestart = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0

[program:nginx]
command =  nginx -g 'daemon off;'
autostart = true
autorestart = true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0